### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by songweige** [chrisjmccormick/inspect_word2vec#4]
Sry but when I was trying to load the .bin file, I met the following error:
> model = gensim.models.Word2Vec.load_word2vec_format('GoogleNews-vectors-negative300.bin', >binary=True)
>Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
>  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1308, in >load_word2vec_format
>    raise DeprecationWarning("Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format >instead.")
>DeprecationWarning: Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.

I also tried using module KeyedVectors, which didn't work either. And seems met a encoding problem.

**Comment by songweige** [comment]
Ooooops, I fixed this.
There are some other data added in my .bin file by design
So I changed the data file and it works
